### PR TITLE
revising test suit to absolute minimum

### PR DESCRIPTION
**Pull request by kkmann**
WIP, feel free to add commits. one commit per file plz. add todos if you find anything.

### CODE REVIEW

**Comment by kkmann** [comment]
Current test set is pretty inefficient and crappy. I started a complete overhaul. Main problems: test_that clauses not specific enough or don't do what they claim to do; to much calls to minimize() with full precision. We can easily make this faster and better by being more specific. Have a look at the files I changed already. Will continue to work on this but would be happy if you joined in @MatheMax.

**Comment by kkmann** [comment]
okay, we can work from here. aim should be to get coverage back up to the previous value and to revise every single use of minimize().

**Comment by MatheMax** [comment]
I'm in! But most of the time is taken by the vignette, not the tests, I think

**Comment by kkmann** [comment]
that's why i removed it from the build process temporarily

**Comment by MatheMax** [comment]
> 
> 
> Main problems: test_that clauses not specific enough or don't do what they claim to do


What is the concrete problem here?

**Comment by kkmann** [comment]
@MatheMax good job, thx!

**Pull request merged**
