### PR TITLE
Added n1 penalization

### PR DESCRIPTION
**Pull request by MatheMax**
... and interpolation via cubic spline. 
Indeed, that makes the package a little bit faster
However, we have to be careful if it destroys any output.

### CODE REVIEW

**Comment by kkmann** [comment]
could you elaborate? a) how exactly does cubic interpolation speed things up b) why include it in this PR and most importantly c) how do we make sure that the cubic interpolation does not lead to overshooting issues (which was the initial motivation for using linear interpolation.

**Comment by MatheMax** [comment]
a) I think that the "true" functions are quite smooth and cubic interpolation produces smoother functions. Therefore, I expect fewer iterations but I'll check this
b) You're right, I should have done two PRs
c) I think this is related to a). As long as we gain (very little) speed and nothing goes wrong, why not doing it?

**Comment by MatheMax** [comment]
@kkmann I reverted the interpolation and will create a new branch to investigate this

**Comment by kkmann** [comment]
I am currently working on a proper namespace and trying to figure out what we actually need to export etc. Also, our score naming is a bit random atm. 
My problem with PenaltyXYZ is that it implies sole usage in the objective function. However, one might also consider imposing constraints on n1. So why not call this 'N1' instead - would be more in line with AverageN2 and SmoothnessN2, right?

**Comment by kkmann** [comment]
how would you feel about unifying the documentation for all pre-implemented scores in a single .rd file?

**Comment by MatheMax** [comment]
> 
> 
> how would you feel about unifying the documentation for all pre-implemented scores in a single .rd file?

could simplify consistency but also become a very large file -> confusing
isn't the idea of roxygen to have the documentation above the corresponding code?

**Comment by kkmann** [comment]
> could simplify consistency but also become a very large file -> confusing

well, it would just be the .rd (you can combine documentation explicitly using roxygen)


>  isn't the idea of roxygen to have the documentation above the corresponding code?

would still be the case (I am not suggesting to combine the .R files). My main point is that the evaluate methods all do the same, and we only have a few conditional scores, so why not list them in one place?

**Pull request merged**
