### PR TITLE
Summary

### PR DESCRIPTION
**Pull request by MatheMax**
Now, summary has 4 rows:

1. first-stage parameters
2. n2-pivots
3. c2-pivots
4. unconditional scores (optional)

Is this a good compromise?

### CODE REVIEW

**Comment by kkmann** [comment]
@MatheMax can you quickly cp an example output?

**Comment by MatheMax** [comment]
> 
> 
> @MatheMax can you quickly cp an example output?

@kkmann :
TwoStageDesign with:
 n1 c1f c1e 
 50   0   2 

n2-pivots:
50 45 40 35 30

c2-pivots:
2 1.5 1 0.5 0

Unconditional scores:
    Power 
0.7228507

**Comment by MatheMax** [comment]
created by the code:
> d <- TwoStageDesign(50, 0, 2, c(50,45,40,35,30), seq(2,0,length.out = 5))
> pow <- Power(Normal(), PointMassPrior(.3,1))
> summary(d, "Power"= pow)

**Comment by kkmann** [comment]
thx, I agree in principle but would prefer a denser layout (mind that this is intended for working with the interactive command line). I.e

```
TwoStageDesign with:
n1: 50, early futility: x1 < 0.00, early efficacy: x1 > 2.00
n2-pivots:  50,   945,   40,   35,   30
c2-pivots:   2.0,   1.5,  1.0,  0.5,  0.0

Power:                 0.723
<some other score> : 120.732
```

in particular:

- proper rounding/formatting via `sprintf` eg. `sprintf("%9.3f")` gives you a fixed length float with two significant digits etc...
- align figures properly...
- the `glue` package might also come in hand to format this quickly (see current class printing)

**Comment by MatheMax** [comment]
> 
> 
> thx, I agree in principle but would prefer a denser layout (mind that this is intended for working with the interactive command line). I.e
> 
> ```
> TwoStageDesign with:
> n1: 50, early futility: X1 < 0.00, early efficacy: X1 > 2.00
> n2-pivots:  50,   945,   40,   35,   30
> c2-pivots:   2.0,   1.5,  1.0,  0.5,  0.0
> 
> Power:                 0.723
> <some other score> : 120.732
> ```
> 
> in particular:
> 
>     * proper rounding/formatting via `sprintf` eg. `sprintf("%9.3f")` gives you a fixed length float with two significant digits etc...
> 
>     * align figures properly...
> 
>     * the `glue` package might also come in hand to format this quickly (see current class printing)

@kkmann I hope the latest implementation is fine

**Comment by kkmann** [comment]
did you test it with 2/3 scores? could you share some example output plz?

**Comment by MatheMax** [comment]
> did you test it with 2/3 scores? could you share some example output plz?

summary(TwoStageDesign(50, 2/3, 7/3, rep(50,5), seq(2,0,length.out = 5)), "Power"=Power(Normal(), PointMassPrior(.3,1)), "ESS"=ExpectedSampleSize(Normal(), PointMassPrior(.4,1)))


TwoStageDesign with:
n1:  50,	early futility: X1 < 0.67,	early efficacy: X1 > 2.33
n2-pivots:  50  50  50  50  50
c2-pivots: 2.0 1.5 1.0 0.5 0.0

Power: 0.599
ESS: 76.967

**Comment by kkmann** [comment]
how does that behave for one-stage gs designs designs, i think thats the reason i removed it in the first place since it was automatically consistent by just reporting the uncondiitonal scores ;) ?

**Comment by MatheMax** [comment]
> 
> 
> how does that behave for one-stage gs designs designs, i think thats the reason i removed it in the first place since it was automatically consistent by just reporting the uncondiitonal scores ;) ?

I think it is consistent ;)

> summary(GroupSequentialDesign(50,0,2,50,2,5), "Power"=Power(Normal(),PointMassPrior(.3,1)))
GroupSequentialDesign with:
n1:  50,	early futility: X1 < 0.00,	early efficacy: X1 > 2.00
n2-pivots:  50
c2-pivots: 2.0 2.0 2.0 2.0 2.0

Power: 0.501


> summary(OneStageDesign(50,2), "Power"=Power(Normal(),PointMassPrior(.3,1)))
OneStageDesign with:
n1:  50,	early futility: X1 < 2.00,	early efficacy: X1 > 2.00
n2-pivots:   0
c2-pivots: NaN

Power: 0.309

**Comment by kkmann** [comment]
@MatheMax careful with sprintf, you used floating ppoint formatting for all numbers ;) also %1.2f is not useful - the specifications are a bit dounting but very helpful ;)

WIP: include c1e + epsilon / c1f - epsilon in the list, conditional scores?

**Comment by kkmann** [comment]
```
summary(opt_ts$design)
TwoStageDesign: n1 =  22; early-futility = 0.59 < X1 < 1.99 = early-efficacy
      x1:  0.59  0.61  0.71  0.86  1.07  1.29  1.52  1.72  1.88  1.97  1.99
  c2(x1):  +Inf +1.86 +1.78 +1.65 +1.46 +1.23 +0.94 +0.60 +0.26 -0.02  -Inf
  n2(x1):     0    40    38    34    28    23    18    15    11     8     0
```

**Comment by MatheMax** [comment]
@kkmann current version: 

```
summary(opt_ts$design, "CP"=cp, "Power" = pow, "ESS" = ess)
TwoStageDesign: n1 =  22 
            futility |            continue           | efficacy
        x1:     0.50 |  0.57  0.84  1.25  1.65  1.92 |  1.99
    c2(x1):      Inf |  1.97  1.72  1.29  0.74  0.14 |  -Inf
    n2(x1):        0 |    32    29    23    16    10 |     0
    CP(x1):     0.00 |  0.62  0.67  0.73  0.81  0.87 |  1.00
     Power:      0.804
       ESS:     31.548
```

**Pull request merged**
