### PR TITLE
Split minimize

### PR DESCRIPTION
**Pull request by kkmann**
minimize() has grown fat over time; I suggest splitting it in minimize() and postprocess() where postprocess() takes the output from minimize and and performs postprocessing. 

Maybe we should even make both functions generic and implement a special method for the onestagedesign.

### CODE REVIEW

**Comment by kkmann** [comment]
WIP, not ready yet

**Comment by kkmann** [comment]
cf. #109 
@MatheMax do you think you can finish this + add the relevant tests?

I'd suggest moving postprocess etc. to a new .R file and create a separate test_postprocess.R

Ideally, we would also implement minimize and .postprocess() as methods dispatching to a specialized method for OneStageDesigns to get rid of that if/else. But I'd do that in a separate step ;)

**Comment by MatheMax** [comment]
@kkmann this should work now
I don't know all the gaps in the test coverage but I'll add a separate testing PR after all upcoming changes

**Comment by kkmann** [comment]
is this ready? quick look: the onestage stuff is still commented out. I'd prefer to have everything ready in one PR. Otherwise looking good.

**Comment by MatheMax** [comment]
Sorry, I missunderstood the sentence with the separate step.
Now the OneStage stuff is included.

**Comment by kkmann** [comment]
cool, thx - I opened it, so feel free to approve and merge ;)

**Pull request merged**
