### PR TITLE
Revise rounding interface

### PR DESCRIPTION
**Pull request by kkmann**
working on the n2/n1 rounding issue cf. #109

### CODE REVIEW

**Comment by kkmann** [comment]
@MatheMax could you have a look at this? 

a) do you agree that this is a more intuitive way to address the whole rounding issue
b) any ideas why all the tests stop working? naively, I'd think that my changes should not affect the optimization process at all oO

**Comment by kkmann** [comment]
okay, so the problem with the new idea is that we need to make all score evaluations aware of the context (optimization or not). 
The current system is imho unnecessarily complex. I'd say let's rename 'specific' to 'optimization' in evaluate(). we can then implement this as optional argument (default = FALSE) for both conditional/unconditional scores.

**Comment by MatheMax** [comment]
alright, give me a try!

**Comment by kkmann** [comment]
okay, more complex than I thought, I am scrapping this and starting from scratch

**Pull request closed without merging**
