### PR TITLE
JSS Paper Vignette

### PR DESCRIPTION
**Pull request by MatheMax**
add jss paper as vignette

### CODE REVIEW

**Comment by kkmann** [comment]
@MatheMax I can't make that work for me (its not covered by the test because they don't recognize it as vignette). R vignettes need to be in the same .Rmd format to work properly, i.e. render to HTML.

**Comment by MatheMax** [comment]
@kkmann 

devtools::build_vignettes() works now.

I followed the JSS proposal (https://www.jstatsoft.org/pages/view/style) "How can I turn my JSS paper into an R package vignette?" where it is recommended to use Sweave.

And I do not think that we can render to HTML if we want to use the JSS template. 
Sweave as well as rticles render to PDF, don't they?

**Comment by kkmann** [comment]
devtools still gives me an error (missing latex package). I tried putting rticles in the deps but that does not seem to solve the problem.
```
Error: processing vignette 'adoptr_paper.Rnw' failed with diagnostics:
Running 'texi2dvi' on 'adoptr_paper.tex' failed.
LaTeX errors:
! LaTeX Error: File `ae.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
```
I don't think we should add LaTeX dependencies to our package, the current format also is incompatible with pkgdown. I still feel the easiest way is putting it in a standard (non JSS) markdown file. Happy to merge with pdf though if you make it work somehow!

**Comment by MatheMax** [comment]
@kkmann next trial ;)
Since a rmarkdown::html_vignette does not support cross references, I switched to bookdown
The layout is nicer as well.

**Comment by kkmann** [comment]
Uha, cool thanks - I didn't know that works x)

Will merge and draft a new release - let's treat ourselves to a 0.4.0, shall we? @MatheMax I will let you know once it is online and referrentiable so that you can update the responses.

**Review by kkmann — APPROVED** [review]

**Pull request merged**
